{
    "name": "Apartment Rental Management",
    "version": "19.0.5.1.0",
    "category": "Real Estate",
    "summary": "Short and long-term apartment rentals, contracts, signatures and invoicing",
    "author": "Community",
    "license": "LGPL-3",
    "depends": ["account", "mail", "portal"],
    "data": [
        "security/rental_security.xml",
        "security/ir.model.access.csv",
        "data/rental_sequence.xml",
        "data/rental_cron.xml",
        "data/rental_mail_template.xml",
        "report/rental_contract_report.xml",
        "report/rental_notice_report.xml",
        "views/rental_contract_template_views.xml",
        "views/rental_application_views.xml",
        "views/rental_property_views.xml",
        "views/rental_unit_views.xml",
        "views/rental_contract_views.xml",
        "views/rental_charge_views.xml",
        "views/rental_notice_views.xml",
        "views/account_move_views.xml",
        "views/rental_portal_templates.xml",
        "views/rental_menus.xml",
    ],
    "application": True,
    "installable": True,
}
