from . import account_move
from . import ir_attachment
from . import rental_billing_line
from . import rental_application
from . import rental_charge
from . import rental_contract
from . import rental_contract_template
from . import rental_notice
from . import rental_property
from . import rental_unit
